// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAkZSSpMqCvR6i0XU6X21Nd52l0w7PuFM',
    appId: '1:183970765607:web:707789c3a949a6a6b1a702',
    messagingSenderId: '183970765607',
    projectId: 'splitpay-58d73',
    authDomain: 'splitpay-58d73.firebaseapp.com',
    storageBucket: 'splitpay-58d73.firebasestorage.app',
    measurementId: 'G-5HMMZEXZRX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3z4CySOHTt17v1oYNQkD_pm8vqEoOlxQ',
    appId: '1:183970765607:android:dd95fa68cffbc2e9b1a702',
    messagingSenderId: '183970765607',
    projectId: 'splitpay-58d73',
    storageBucket: 'splitpay-58d73.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVpjqkkQGKD4CpB0-zZ7isZ866wd1w7u0',
    appId: '1:183970765607:ios:a2fcdd35b9d807bab1a702',
    messagingSenderId: '183970765607',
    projectId: 'splitpay-58d73',
    storageBucket: 'splitpay-58d73.firebasestorage.app',
    iosBundleId: 'com.SplitPay.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVpjqkkQGKD4CpB0-zZ7isZ866wd1w7u0',
    appId: '1:183970765607:ios:a2fcdd35b9d807bab1a702',
    messagingSenderId: '183970765607',
    projectId: 'splitpay-58d73',
    storageBucket: 'splitpay-58d73.firebasestorage.app',
    iosBundleId: 'com.SplitPay.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAkZSSpMqCvR6i0XU6X21Nd52l0w7PuFM',
    appId: '1:183970765607:web:5d95caa48c3fa872b1a702',
    messagingSenderId: '183970765607',
    projectId: 'splitpay-58d73',
    authDomain: 'splitpay-58d73.firebaseapp.com',
    storageBucket: 'splitpay-58d73.firebasestorage.app',
    measurementId: 'G-4R20R8ZHKM',
  );
}
